config/routes.rb
Rails.application.routes.draw do
  root "merchants#index"

  resources :merchants, only: [:index, :show] do
    get :chart_data, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/disbursement.rb
# == Schema Information
#
# Table name: disbursements
#
#  id                 :bigint           not null, primary key
#  reference          :string
#  merchant_reference :string           not null
#  amount             :decimal(10, 2)
#  fee                :decimal(10, 2)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
class Disbursement < ApplicationRecord
  belongs_to :merchant, foreign_key: :merchant_reference, primary_key: :reference
  has_many :orders, foreign_key: :disbursement_reference, primary_key: :reference

  before_create :check_previous_monthly_fee
  before_create :generate_reference

  def process_orders(order_ids)
    orders        = Order.where(id: order_ids)
    orders_values = orders.pluck('SUM(to_pay)', 'SUM(fee)').map { |to_pay, fee| { to_pay: to_pay, fee: fee } }.first

    update(amount: orders_values[:to_pay], fee: orders_values[:fee])
    orders.update_all(disbursement_reference: reference, status: :processed)
  end

  private

  def check_previous_monthly_fee
    previous_records_on_month = merchant.disbursements.where('created_at >= ?', self.created_at.beginning_of_month).present?

    return if previous_records_on_month
    last_month_disbursements = merchant.last_month_disbursements(created_at)

    return if last_month_disbursements.empty?
    total_disbursed_last_month = last_month_disbursements.sum(:fee)

    return if total_disbursed_last_month >= merchant.minimum_monthly_fee
    merchant.monthly_fees.create(month: created_at.beginning_of_month, amount: merchant.minimum_monthly_fee - total_disbursed_last_month )
  end

  def generate_reference
    self.reference = SecureRandom.alphanumeric(10)
  end
end

app/models/merchant.rb
# == Schema Information
#
# Table name: merchants
#
#  id                     :bigint           not null, primary key
#  guid                   :string           not null
#  reference              :string           not null
#  email                  :string
#  live_on                :datetime
#  disbursement_frequency :integer
#  minimum_monthly_fee    :decimal(10, 2)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class Merchant < ApplicationRecord
  has_many :orders, foreign_key: :merchant_reference, primary_key: :reference
  has_many :disbursements, foreign_key: :merchant_reference, primary_key: :reference
  has_many :monthly_fees, foreign_key: :merchant_reference, primary_key: :reference

  enum disbursement_frequency: { daily: 0, weekly: 1 }

  validates :guid, :reference, presence: true, uniqueness: true

  def perform_disbursements
    orders_data = orders.pending.select(:id, :created_at)
    daily? ? perform_daily_disbursement(orders_data) : perform_weekly_disbursement(orders_data)
  end

  def last_month_disbursements(date)
    disbursements.where(created_at: (date - 1.month).beginning_of_month..(date - 1.month).end_of_month)
  end

  def monthly_disbursements_sum
    return if minimum_monthly_fee == 0
    disbursements.group("DATE_TRUNC('month', created_at)").sum(:fee).map { |date, sum| { date => [minimum_monthly_fee.to_f, sum.to_f] } }
  end

  private

  def perform_daily_disbursement(orders_data)
    orders_data.by_day.each do |date, orders|
      process_disbursements(date, orders)
    end
  end

  def perform_weekly_disbursement(orders_data)
    start_week_day = live_on.strftime("%A").downcase.to_sym

    orders_data.by_week_day(start_week_day).each do |date, orders|
      process_disbursements(date, orders)
    end
  end

  def process_disbursements(date, orders)
    disbursement = disbursements.create(created_at: date)
    order_ids    = orders.pluck(:id)

    disbursement.process_orders(order_ids)
  end
end

app/models/monthly_fee.rb
# == Schema Information
#
# Table name: monthly_fees
#
#  id                 :bigint           not null, primary key
#  merchant_reference :string           not null
#  month              :date
#  amount             :decimal(, )
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
class MonthlyFee < ApplicationRecord
  belongs_to :merchant, foreign_key: :merchant_reference, primary_key: :reference
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id                     :bigint           not null, primary key
#  guid                   :string           not null
#  status                 :integer          default("pending"), not null
#  amount                 :decimal(10, 2)
#  fee                    :decimal(10, 2)
#  to_pay                 :decimal(10, 2)
#  merchant_reference     :string           not null
#  disbursement_reference :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class Order < ApplicationRecord
  belongs_to :merchant, foreign_key: :merchant_reference, primary_key: :reference
  belongs_to :disbursement, foreign_key: :disbursement_reference, primary_key: :reference, optional: true

  enum status: { pending: 0, processed: 1, failed: 2 }

  scope :by_day, ->{ group_by(&:created_at).sort  }
  scope :by_week_day, ->(start) { group_by { |o| o.created_at.beginning_of_week(start) }.sort  }

  after_create :generate_fee

  def generate_fee
    fee = self.class.calculate_fee(amount)
    update(to_pay: (amount - fee), fee: fee)
  end

  def self.calculate_fee(amout_value)
    case amout_value
    when 0..49.99
      (amout_value * 0.01).round(2)
    when 50..299.99
      (amout_value * 0.0095).round(2)
    else
      (amout_value * 0.0085).round(2)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show, :chart_data]
  before_action :set_group_param, only: [:show, :chart_data]

  def index
    @merchants = Merchant.all
  end

  def show; end

  def chart_data
    @chart_data =  [
      {
        name: "Orders",
        data: parse_chart_data(@merchant.orders)
      },
      {
        name: "Disbursements",
        data: parse_chart_data(@merchant.disbursements)
      }
    ]
    render json: @chart_data
  end

  def update_chart_data
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('chart_data', partial: 'chart_data', locals: { merchant: @merchant })
      end
    end
  end

  private

  def set_merchant
    @merchant =Merchant.includes(:orders, :disbursements).find(params[:id])
  end

  def set_group_param
    @group_param = params[:group] || "group_by_month"
    @date_format =
      case @group_param
      when "group_by_day"
        "%d/%b/%y"
      when "group_by_week"
        "%d/%b/%y"
      when "group_by_month"
        "%b/%y"
      when "group_by_year"
        "%Y"
      end
  end

  def parse_chart_data(data)
    data.send(@group_param) { |u| u.created_at }.to_h { |k, v| [k.strftime(@date_format), v.pluck(:amount).sum] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GioPay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/merchants/_chart_data.html.erb
<%= column_chart chart_data_merchant_path(merchant, group: group_by) %>

app/views/merchants/index.html.erb
<h1 class="text-3xl font-bold underline">
  All Merchants
</h1>
<table class="w-full border-collapse">
  <thead>
    <tr>
      <th class="py-2 px-4 border-b">Reference</th>
      <th class="py-2 px-4 border-b">Live On</th>
      <th class="py-2 px-4 border-b" colspan="2">Disbursements</th>
      <th class="py-2 px-4 border-b">Minimum Monthly Fee</th>
      <th class="py-2 px-4 border-b"></th>
    </tr>
    <tr>
      <th class="py-2 px-4 border-b"></th>
      <th class="py-2 px-4 border-b"></th>
      <th class="py-2 px-4 border-b">Frequency</th>
      <th class="py-2 px-4 border-b">Total</th>
      <th class="py-2 px-4 border-b"></th>
      <th class="py-2 px-4 border-b"></th>
    </tr>
  </thead>
  <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td class="py-2 px-4 border-b"><%= merchant.reference %></td>
        <td class="py-2 px-4 border-b"><%= merchant.live_on %></td>
        <td class="py-2 px-4 border-b"><%= merchant.disbursement_frequency.capitalize %></td>
        <td class="py-2 px-4 border-b"><%= merchant.disbursements.count %></td>
        <td class="py-2 px-4 border-b"><%= number_to_currency(merchant.minimum_monthly_fee, unit: "€") %></td>
        <td class="py-2 px-4 border-b"><%= link_to 'View', merchant_path(merchant) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/merchants/show.html.erb
<div class="container mx-auto">
    <div class="flex flex-row flex-wrap py-4">
        <aside class="w-14">
            <div class="sticky top-0 p-4 w-full">
                <ul class="flex flex-col overflow-hidden">
                    <h1 class="text-3xl font-bold mb-4">
                      <%= @merchant.reference %>
                    </h1>

                    <select data-controller="charts" data-action="charts#load_chart" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
                      <% %w[day week month year].each do |group| %>
                        <option value="<%= merchant_path(@merchant, group: "group_by_#{group}") %>">By <%= group %></option>
                      <% end %>
                    </select>
                </ul>
            </div>
        </aside>
        <main role="main" class="w-full">
            <div class="grid grid-cols-2 gap-4 mb-8">
              <div class="p-6 bg-white rounded shadow">
                <h2 class="text-xl font-semibold mb-2">Orders</h2>
                <p class="text-gray-600">
                  <%= @merchant.orders.count %>
                </p>
              </div>

              <div class="p-6 bg-white rounded shadow">
                <h2 class="text-xl font-semibold mb-2">Disbursements</h2>
                <p class="text-gray-600">
                  <%= @merchant.disbursements.count %>
                </p>
              </div>
            </div>

            <turbo-frame id="chart_data">
              <%= render partial: 'chart_data', locals: { merchant: @merchant, group_by: @group_param } %>
            </turbo-frame>
        </main>
    </div>
</div>